name: Update Quote

on:
  schedule:
    - cron: "59 * * * *"
  workflow_dispatch:

jobs:
  update-quote:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Remove old quote from README
        run: sed -i '/#### Hourly (anime) quote/q' README.md

      - name: Fetch new quote
        id: new-quote
        run: |
          data=$(curl --silent https://quotes.terworking.workers.dev/1 | jq .data[0])
          echo "character=$(jq -r .character <<< $data)" >> $GITHUB_OUTPUT
          echo "show=$(jq -r .show <<< $data)" >> $GITHUB_OUTPUT

          # replace double quotes with single quote
          quote=$(jq -r .quote <<< $data)
          quote=$(tr '"' "'" <<< $quote)
          echo "quote=$quote" >> $GITHUB_OUTPUT

      - name: Add new quote to README
        run: |
          python ./process-quote.py \
            "${{ steps.new-quote.outputs.character }}" \
            "${{ steps.new-quote.outputs.show }}" \
            "${{ steps.new-quote.outputs.quote }}" >> README.md

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          commit_message: Update README quote
          file_pattern: README.md
